// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryPattern.Controllers;

namespace RepositoryPattern.Migrations
{
    [DbContext(typeof(StudentRepoContext))]
    [Migration("20191009091113_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RepositoryPattern.Controllers.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sage");

                    b.Property<string>("Sdept");

                    b.Property<string>("Sname");

                    b.Property<string>("Ssection");

                    b.Property<int?>("TeacherTid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherTid");

                    b.ToTable("student");
                });

            modelBuilder.Entity("RepositoryPattern.Controllers.Models.Teacher", b =>
                {
                    b.Property<int>("Tid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Tage");

                    b.Property<string>("Tname");

                    b.HasKey("Tid");

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("RepositoryPattern.Controllers.Models.Student", b =>
                {
                    b.HasOne("RepositoryPattern.Controllers.Models.Teacher")
                        .WithMany("_students")
                        .HasForeignKey("TeacherTid");
                });
#pragma warning restore 612, 618
        }
    }
}
